#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <random>
#include <numeric>
#include <limits>
#include <cctype>
#include <fstream>
#include <sstream>
#include <cstdio>
#include <chrono>
#include <cstdlib>
#include <chrono>
#include <sstream>
#include <cstring>
#include <cerrno>
#include <fcntl.h>
#include <sys/stat.h>
#include <deque>
#include <list>

using std::bad_alloc;
using std::bad_exception;
using std::cin;
using std::copy;
using std::cout;
using std::deque;
using std::domain_error;
using std::endl;
using std::exception;
using std::fixed;
using std::getline;
using std::ifstream;
using std::invalid_argument;
using std::left;
using std::length_error;
using std::list;
using std::move;
using std::mt19937;
using std::numeric_limits;
using std::ofstream;
using std::out_of_range;
using std::overflow_error;
using std::random_device;
using std::range_error;
using std::remove;
using std::remove_if;
using std::right;
using std::runtime_error;
using std::setprecision;
using std::setw;
using std::sort;
using std::streamsize;
using std::string;
using std::stringstream;
using std::swap;
using std::to_string;
using std::underflow_error;
using std::uniform_int_distribution;
using std::vector;
using std::istringstream;
using std::allocator;
using std::allocator_traits;
using std::uninitialized_copy;
using std::max;